version: "3.8"
services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      TZ: "Asia/Taipei"
      PGTZ: "Asia/Taipei"
    expose:
      - 5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    container_name: keycloak_db
    networks:
      - keycloak-network
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KC_PROXY: edge
      KC_HOSTNAME: $KEYCLOAK_HOSTNAME
      KC_HOSTNAME_ADMIN_URL: "https://$KEYCLOAK_HOSTNAME"
      KC_HOSTNAME_STRICT: "false"
      KEYCLOAK_ADMIN: $KEYCLOAK_ADMIN
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      # https://www.keycloak.org/server/db#_relevant_options
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      # KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: $POSTGRES_DB
      KC_DB_USERNAME: $POSTGRES_USER
      KC_DB_PASSWORD: $POSTGRES_PASSWORD
      KC_DB_SCHEMA: public
    # 使用 dev 的時候，不會強迫 hostname 在 iframe 內使用https
    # https://www.keycloak.org/server/hostname
    # command: "start-dev"
    command: "start"
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    container_name: keycloak
    networks:
      - keycloak-network
      - demo
    restart: always

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volumes/dbdata'
    external: false

networks:
  keycloak-network:
    driver: bridge
  demo:
    external: true
